spring:
  application:
    name: movie-catalog-service
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: vikas
    #initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
server:
  port: 8000
eureka:
      client:
        registerWithEureka: true
        fetchRegistry: true
        service-url:
          defaultZone: http://localhost:8761/eureka
      instance:
        hostname: localhost



