spring:
  application:
    name: movie-catalog-service
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
     format_sql: true
    ddl-auto: update
server:
  port: 8000
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:mem:testdb
      username:  sa
      password:
      driverClassName: org.h2.Driver
eureka:
      client:
        registerWithEureka: true
        fetchRegistry: true
        service-url:
          defaultZone: http://localhost:8761/eureka
      instance:
        hostname: localhost



