spring:
  application:
    name: book-info-service
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      format_sql: true
      ddl-auto: update
server:
  port: 8001
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:mem:testdb
      username:  sa
      password:
      driverClassName: org.h2.Driver
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka





